language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
script: npm test
after_script: npm run test-coverage && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: mugo@forfuture.co.ke
  api_key:
    secure: OwPRUPXcE/i7fgo6pE2xmu3rxaloaegsadRiRPtZlPF1bCFbOYqIk33fsWUcohoW2bY4nq1C116sNumWBL1oi0AQg2Sk1nOzRXM4Ysc8rpwGP6HHEcmSsCWSRckvePn8ReO6t394RJzVPZ08SoJ7TwQtcsTMsJlv/Y2w1jJjv5Y=
  on:
    tags: true
    repo: forfutureLLC/node-simple-argparse
    branch: master
